Views/Shared/Components/CartSummaryViewComponent.cs
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Views.Shared.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public CartSummaryViewComponent(Basket basketservice)
        {
            basket = basketservice;
        }
      public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Views/Shared/ProjectSummary.cshtml
@{
}

@model Book
<div class="bg-light">
    <h3 class="align-content-center">@Model.Title</h3>
    <span class="badge bg-info" style="float:right">Price: $@Model.Price</span>
</div>

<ul>
    <li><mark>Author: @Model.Author</mark></li>
    <li>Category: @Model.Category</li>
    <li>Isbn: @Model.Isbn</li>
    <li>Page Count: @Model.PageCount</li>
    <li>Publisher: @Model.Publisher</li>
    <li>Classificaiton: @Model.Classification</li>
</ul>
<form method="post" asp-page="/cart">
    <input type="hidden" asp-for="@Model.BookId"/>
    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
     <span class="card-text"><button type="submit" class="btn btn-success btn-sm float-end" >Add to Cart</button></span>
</form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />

</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2" data-toggle="tooltip" title="Really It's not amazon'!">Not Amazon</span>
        <a asp-page="/cart" class="fa fa-shopping-cart float-end  p-2"  style="font-size:24px;color:white; text-decoration:none"></a><vc:cart-summary></vc:cart-summary>
    </div>
        <br />

        <div class="container">
            <div  id="category" class="row m-1 p-1">
                <div class="col-3">
                    <vc:Categories></vc:Categories>
                </div>
                <div class="col-lg-9">

                 @RenderBody()
                </div>

            </div>
        </div>

     
        <br />

    </body>
</html>